version: '3.7'

services:
  react-dev-server:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    volumes:
      - "./my-app:/app"
    ports:
      - "3000:3000"
  
  ros-2:
    build:
      context: .
      dockerfile: ROS2.Dockerfile
    ports:
      - "9090:9090"